# Generated by Django 2.2.1 on 2019-07-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190718_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
