# Generated by Django 2.2.1 on 2019-07-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='index_img',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
